---

- name: Auto git
  hosts: localhost
  tasks:
    - name: Add everything
      command: git add .

    - name: Commit everything
      command: git commit -m "{{ commit_message }}"

    - name: Push
      command: git push origin main
